<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54621" started-at="2019-06-12T16:41:22Z" finished-at="2019-06-12T16:42:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54621" started-at="2019-06-12T16:41:22Z" finished-at="2019-06-12T16:42:16Z">
      <class name="testngTest.TestCases">
        <test-method status="PASS" signature="testngSetup(java.lang.reflect.Method)[pri:0, instance:testngTest.TestCases@35599228]" name="testngSetup" is-config="true" duration-ms="20157" started-at="2019-06-12T22:11:22Z" finished-at="2019-06-12T22:11:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testngTest.TestCases.Addition_Of_Two_Numbers() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testngSetup -->
        <test-method status="PASS" signature="Addition_Of_Two_Numbers()[pri:0, instance:testngTest.TestCases@35599228]" name="Addition_Of_Two_Numbers" duration-ms="11284" started-at="2019-06-12T22:11:42Z" finished-at="2019-06-12T22:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Addition_Of_Two_Numbers -->
        <test-method status="PASS" signature="testngClean(org.testng.ITestResult)[pri:0, instance:testngTest.TestCases@35599228]" name="testngClean" is-config="true" duration-ms="2692" started-at="2019-06-12T22:11:53Z" finished-at="2019-06-12T22:11:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Addition_Of_Two_Numbers status=SUCCESS method=TestCases.Addition_Of_Two_Numbers()[pri:0, instance:testngTest.TestCases@35599228] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testngClean -->
        <test-method status="PASS" signature="testngSetup(java.lang.reflect.Method)[pri:0, instance:testngTest.TestCases@35599228]" name="testngSetup" is-config="true" duration-ms="5729" started-at="2019-06-12T22:11:56Z" finished-at="2019-06-12T22:12:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testngTest.TestCases.Failed_Test_Case() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testngSetup -->
        <test-method status="FAIL" signature="Failed_Test_Case()[pri:0, instance:testngTest.TestCases@35599228]" name="Failed_Test_Case" duration-ms="3025" started-at="2019-06-12T22:12:02Z" finished-at="2019-06-12T22:12:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<1> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at pageClasses.PageObject_FormFilling.failTC(PageObject_FormFilling.java:89)
	at testngTest.TestCases.Failed_Test_Case(TestCases.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Failed_Test_Case -->
        <test-method status="PASS" signature="testngClean(org.testng.ITestResult)[pri:0, instance:testngTest.TestCases@35599228]" name="testngClean" is-config="true" duration-ms="849" started-at="2019-06-12T22:12:05Z" finished-at="2019-06-12T22:12:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Failed_Test_Case status=FAILURE method=TestCases.Failed_Test_Case()[pri:0, instance:testngTest.TestCases@35599228] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testngClean -->
        <test-method status="PASS" signature="testngSetup(java.lang.reflect.Method)[pri:0, instance:testngTest.TestCases@35599228]" name="testngSetup" is-config="true" duration-ms="5611" started-at="2019-06-12T22:12:05Z" finished-at="2019-06-12T22:12:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testngTest.TestCases.Sample_Form_Filling() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testngSetup -->
        <test-method status="PASS" signature="Sample_Form_Filling()[pri:0, instance:testngTest.TestCases@35599228]" name="Sample_Form_Filling" duration-ms="4380" started-at="2019-06-12T22:12:11Z" finished-at="2019-06-12T22:12:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Sample_Form_Filling -->
        <test-method status="PASS" signature="testngClean(org.testng.ITestResult)[pri:0, instance:testngTest.TestCases@35599228]" name="testngClean" is-config="true" duration-ms="858" started-at="2019-06-12T22:12:15Z" finished-at="2019-06-12T22:12:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Sample_Form_Filling status=SUCCESS method=TestCases.Sample_Form_Filling()[pri:0, instance:testngTest.TestCases@35599228] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testngClean -->
      </class> <!-- testngTest.TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
